TRAINING:
  EPOCHS: 30
  TRAIN_PORTION: 0.6
  VAL_PORTION: 0.20
  BATCH_SIZE: 16
  LEARNING_RATE: 0.00001
  WEIGHT_DECAY: 0.0001
  DEVICE: "cuda:0"
  IMAGE_DIMENSIONS:
    HEIGHT: 270
    WIDTH: 480
  REFERENCE_IMAGE: True

MODEL:
  SNOWRANKER:
    KERNEL_SIZE: 5

