TRAINING:
  EPOCHS: 50
  TRAIN_PORTION: 0.5
  VAL_PORTION: 0.25
  BATCH_SIZE: 64
  LEARNING_RATE: 1.0e-6
  WEIGHT_DECAY: 1.0e-3
  DEVICE: "cuda:0"
  EARLY_STOPPING: 5
  LOSS: "PairWise"
  QUICK_DEV_RUN: False
IMAGE:
  HEIGHT: 224
  WIDTH: 224
  REFERENCE_IMAGE: False
  NORMALIZE: True
  HORIZONTAL_FLIP: 0.5
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.25

DATASET:
  SPLIT: "turbine"



MODEL:
  SNOWRANKER:
    KERNEL_SIZE: 5
  VIT:
    PRE_TRAINED: "google/vit-base-patch32-224-in21k"
    DROPOUT: 0.50

WANDB:
  API_KEY:
  USERNAME:
  PROJECT:
  DISABLED: True
  RUN_NAME:
